#+TITLE: blockchain

* https://medium.com/wikidlt/a-complete-list-of-blockchain-platforms-2020-49cf01ee6688
1. Algorand

Algorand is an open-source public blockchain based on a pure proof-of-stake consensus protocol that supports the scalability and transaction finality. Role-Based Asset Control in Algorand lets us use this Blockchain platform for numerous purposes involving asset transfer.

2. BigChainDB

This is not a blockchain platform but rather a Blockchain facilitator which lets us deploy Blockchains with a database containing built-in asset support and rich queries as well as high throughput, supporting a wide range of industries and use cases.

3. Credits

Credits is an open-source, fully decentralized blockchain software protocol. It introduces a unique new consensus algorithm — PoA (Proof of Agreement) based on BFT conception. Best suited for use cases involving microtransactions, mass financial payments and tokens issuing.

4. Chain Core

This platform lets you manage financial assets through a permissioned Blockchain System. With applications mainly in the financial industry, Chain Core can manage any number of independent blockchains by maintaining their ledgers or can act as a blockchain client for different permissioned blockchains.

5. Coco

Coco, Confidential Consortium, is a framework released by Microsoft which aims primarily at improving scalability by providing 1000+ transaction handling. It is compatible with all blockchain platform like Hyperledger Sawtooth, Ethereum, Corda, and Quorum. It also provides Trusted Execution Environments.

6. EOS

Ever heard of a developer-friendly Blockchain? Well EOS is one. Built for both public and private use cases, EOSIO is customizable to suit a wide range of business needs across industries

7. HydraChain

HydraChain is en extension of Ethereum. Leveraging the popularity and scalability of Ethereum it provides us with the creation of Blockchain-based applications by allowing users to develop smart contracts in Python.

8. ICON

ICON provides a decentralized network that allows independent blockchains with different governances to transact with one another without intermediaries. In simple words, It enables cross country payments through Blockchain(s) without depending on Fiats.

9. IOTA

Blockchain for IoT has been given a new definition with this unique Blockchain platform. IOTA enables transactions between machines and IoT devices. The ledger uses a cryptocurrency called mIOTA to account for transactions in its network. IOTA’s Tangle is a system of nodes used for confirming transactions and the crown jewel of IOTA.

10. Lisk

Lisk focuses on the effortless development of Blockchain applications and hence Lisk SDK comes with developer tools, an active community and energy-efficient Blockchain network.

11. Multichain

MultiChain helps organizations to build and deploy blockchain applications with speed. It is being widely used including projects like SAP for Pharmaceuticals, TruBudget, Tagcash KYC, ILSBlockchain

12. NEO

According to their website, Neo is a “non-profit community-based blockchain project that utilizes blockchain technology and digital identity to digitize assets, to automate the management of digital assets using smart contracts, and to realize a “smart economy” with a distributed network.”

13. NEM

NEM’s permissioned private blockchain delivers industry-leading transaction rates for internal ledgers. And its revolutionary consensus mechanism and the Supernode program ensure that NEM’s open, public blockchain can grow without ever compromising throughput or stability.

14. Openchain

Openchain is an open-source distributed ledger technology suited for organizations wishing to issue and manage digital assets in a robust, secure and scalable way. It provides a single authority for verification of transactions. Every organisation has its sole instance of the ledger containing transactions which can be connected if needed.

15. Qtum

Qtum is an open-sourced public blockchain platform equipped with UTXO. Qtum is PoS based with a Decentralized Governance Protocol (DGP) allowing specific blockchain settings to be modified by making use of smart contracts like increasing the block size without the need of a hard fork.

16. Quorum

It is a permissioned Ethereum based Blockchain platform. Ethereum rules the world of public Blockchains and it is only befitting to use the concept, scalability, crypto and the technological aspect of Ethereum in a permissioned way to equip enterprises with a platform they can rely on. It is open source and has decent community support from the Ethereum community.

17. Smilo

Smilo is built on the concept of hybrid Blockchain. In a way, there was a need for the scalability and transparency of the public Blockchain while not being void of security and privacy of an organisation on the whole which gave birth to the concept of hybrid Blockchain. Smilo offers a blockchain platform which supports a combination of hybrid transactions, hybrid smart contracts and hybrid decentralised applications.

18. Stellar

Stellar introduces a way to combine the fiat currency with the digital currency. It is a decentralised platform which lets you hold, send, and swap digital versions of everyday currencies. fast, cross-border transactions between any pair of currencies can be done using Stellar through Its native asset, a digital currency called lumen (XLM).

19. Straitis

Straitis is a blockchain platform designed for particularly Windows/Microsoft environment which lets us develop Blockchain without having to configure our infrastructure. Essentially, every blockchain platform requires setting up of a network infrastructure which requires more effort and time then the actual development of the Blockchain and hence a platform like Straitis comes into play.

20. Tendermint

Tendermint is an Application BlockChain Interface(ABCI) which powers the Cosmos Blockchain platform. In any Blockchain, the basic requirement is of a consensus and the peer-to-peer network configurations but it is obvious that we don’t need to develop these if we want to incorporate Blockchain in our business so Tendermint built an engine which works like an engine for a car. You have to design the layout and the purpose of the car with Cosmos and Tendermint will power it with its engine.

21. Tezos

Tezos is a technology for deploying a blockchain capable of modifying its own set of rules with minimal disruption to the network through an on-chain governance model. It utilizes a Proof-of-Stake based consensus model.

22. Universa

Universa Protocol allows using cutting-edge technical advances such as IoT, BIM and escrow financing, which enable more transparent, trusted and faster transactions, thus granting an opportunity to link all the participants in the city digitization process. Universa mainnet is a global decentralized network offering extremely fast and secure enterprise-level blockchain and data storage services.

23. Waves Platform

It is a crypto-platform for asset/custom token issuance, transfer, and trading on the blockchain. Waves’ technology is designed for companies and developers who want to leverage the security, auditability, verifiability and the trustless execution of transactions and programming logic

24. Xinfin

Xinfin’s Blockchain platform along with its wallet is a Hybrid Blockchain platform which focuses on real-time Cross Border Trade and Finance. The XDC token is the underlying utility token of the XinFin hybrid blockchain and acts as a settlement mechanism for dApps built on the XinFin hybrid blockchain.

25. Zilliqa

With its own smart contract language scilla and being the first public Blockchain to implement sharding in its testnet, Zilliqa is a high-throughput blockchain platform that achieves over 2,828 transactions per second. Moreover, the scalable throughput ensures that Zilliqa’s capacity can continue to grow with the growing number of nodes.
Additionally, I would like to mention 20 more Blockchain platforms which are currently being developed or are in the stage of early deployment.

 - Aion
 - ArcBlock
 - Ardor
 - Blockstream
 - Commerce Block
 - Cardano
 - Credits
 - Elements Blockchain Platform
 - Enigma
 - Eris:db
 - Komodo
 - Loyakk
 - Neblio
 - Nxt
 - Quantstamp
 - RSK
 - Symbiont Assembly
 - Swirlds
 - Tangle
 - Wanchain

* https://www.technoduet.com/a-comprehensive-list-of-blockchain-platforms/
1. Aion

Aion is a third-generation blockchain network that will enable an organization to Federate, Scale and Spoke.

Consensus: Proof-of-Intelligence Staking
language: Aion, Solidity
Website: aion.network
2. ArcBlock

ArcBlock, built with an open standard, is a platform and an ecosystem for building and deploying decentralized blockchain applications.

Consensus: Algorand based
language: -
Website: www.arcblock.io
3. Ardor

Ardor is a blockchain-as-a-service-platform that evolved from the Nxt blockchain.

Consensus: Proof of Stake
language: Java
Website: www.ardorplatform.org
4. Cardano

Cardano, the first blockchain platform to evolve out of a scientific philosophy and a research-first driven approach, is built by a global team of leading academics and engineers.

Consensus: Proof of Stake
language: Plutus
Website: www.cardano.org/en/home
5. Corda

Corda, developed by R3, is an open source blockchain platform to record, manage and synchronise agreements and transfer value. It allows you to build interoperable blockchain networks that transact directly, in strict privacy.

Consensus: Pluggable Consensus
language: Kotlin, Java etc.
Website: www.corda.net
6. Enigma

Enigma is a permissionless peer-to-peer network. With Enigma, “smart contracts” become “secret contracts”, where input data is kept hidden from nodes in the Enigma network that execute code.

Consensus: Proof of Stake
language: Solidity
Website: enigma.co
7. EOS

EOSIO is a free, open-source blockchain software protocol that provides developers and entrepreneurs with a platform on which to build, deploy and run high-performing decentralized applications.

Consensus: Delegated Proof of Stake (dPoS)
language: C++, WebAssembly
Website: eos.io
8. Ethereum

Ethereum, developed by the Ethereum Foundation, is a decentralized platform that runs smart contracts.

Consensus: Proof of Work
language: Solidity, Serpent, LLL
Website: www.ethereum.org
9. Hyperledger Fabric

Hyperledger Fabric is a blockchain framework implementation and one of the Hyperledger projects hosted by The Linux Foundation. It allows components such as consensus and membership services to be plug-and-play.

Consensus: SOLO, Kafka
language: Go, Java
Website: www.hyperledger.org/projects/fabric
10.Hyperledger Sawtooth

Hyperledger Sawtooth is an enterprise blockchain platform for building distributed ledger applications and networks. Sawtooth is an open source project under the Hyperledger umbrella.

Consensus: Proof of Elapsed Time (PoET)
language: Python, C++, Go, Java, JavaScript, Rust etc.
Website: www.hyperledger.org/projects/sawtooth
11. ICON

ICON is a decentralized blockchain network where various blockchain-based independent Communities are connected to form a greater community. At the core of ICON is a high-performance blockchain loopchain.

Consensus: Loop Fault Tolerance (LFT)
language: Python
Website: icon.foundation
12. IOTA

IOTA is a next generation permissionless distributed ledger that utilizes a novel invention, called a “Tangle”, at its core.

Consensus: Coordinator
language: Rust, Go, Javascript, Java, C++
Website: www.iota.org
13. Komodo

Komodo is a secure, independently scalable, and fully interoperable blockchain ecosystem that provides end-to-end blockchain technology solutions.

Consensus: delayed Proof of Work (dPoW)
language: Any
Website: komodoplatform.com
14. Lisk

Lisk is a blockchain application platform created to bring blockchain technology to the world through an SDK (Sidechain Development Kit) written in JavaScript.

Consensus: Delegated Proof of Stake (DPoS)
language: Javascript
Website: lisk.io
15. MultiChain

MultiChain is an off­the­shelf platform for the creation and deployment of private blockchains, either within or between organizations.

Consensus: -
language: Any
Website: www.multichain.com
16. Neblio

A secure, distributed, blockchain platform built for enterprise applications and services.

Consensus: Proof of Stake
language: Java, Javascript, Ruby, Python, Go, C#, PhP, Objective-C
Website: nebl.io
17. NEM

NEM’s blockchain platform was designed and coded from the ground up for scale and speed.

Consensus: Proof of Importance
language: Any
Website: nem.io
18. NEO

NEO, founded in 2014, is a non-profit community-driven blockchain project.

Consensus: Delegated Byzantine Fault Tolerance (dBFT)
language: C#, VB.Net, F#, Java, Kotlin, Python
Website: neo.org
19. Nxt

Nxt is an advanced open source blockchain platform that includes many core-level features, such as a Decentralized Asset Exchange, Marketplace, and Voting system.

Consensus: Proof of Stake
language: -
Website: nxtplatform.org
20. OpenChain

Openchain is an open source distributed ledger technology that is suited for organizations wishing to issue and manage digital assets in a robust, secure and scalable way.

Consensus: Partionned Consensus
language: Any
Website: www.openchain.org
21. Qtum

A decentralized and open-source smart contracts platform and value transfer protocol. Qtum employs a decentralized governance protocol allowing for blockchain parameters like the block size, block time, gas schedules, and the minimum gas price for contracts to be modified without requiring a fork.

Consensus: Proof of Stake
language: Solidity
Website: qtum.org/en
22. Smilo

Smilo is the hybrid blockchain platform that warrants transparency whilst protecting individual’s personal data.

Consensus: Smilo BFT+
language: lidity, Javascript, Java, Python
Website:
23. Stellar

Stellar is open-source, distributed payments infrastructure using blockchain technology.

Consensus: Stellar Consensus Protocol
language: Go, Java, Javascript
Website: www.stellar.org
24. Straitis

Stratis offers full service capabilities for the development, deployment and management of enterprise blockchain applications and solutions utilizing C# on the .Net framework.

Consensus: Proof of Stake
language: C#
Website: stratisplatform.com
25. Tezos

Tezos is a blockchain that can evolve by upgrading itself. Stakeholders vote on amendments to the protocol, including amendments to the voting procedure itself, to reach social consensus on proposals.

Consensus: Proof of Stake
language: Michelson
Website: tezos.com
26. Wanchain

Wanchain supports cross-chain transactions between mainstream public chains, between private chains, and between public and private chains.

Consensus: Proof of Stake
language: Solidity
Website: wanchain.org
27. Waves

Waves Platform is a comprehensive blockchain platform that features fiat gateways, smart contracts, mobile wallet, token issuance, a DEX (decentralized exchange), and more.

Consensus: Proof of Stake
language: RIDE
Website: wavesplatform.com
28. Zilliqa

Zilliqa is a high throughput public blockchain platform designed to scale to thousands of transactions per second.

Consensus: Practical byzantine fault tolerance (PBFT)
language: Scilla
Website: zilliqa.com
* https://www.leewayhertz.com/top-blockchain-platforms/

1. Tezos

Tezos is an open-source and decentralized blockchain network that can perform peer-to-peer transactions and deploy smart contracts. It has a modular architecture and formal upgrade mechanism that allows its network to facilitate formal verification.

Founded by Arthur Breitman and Kathleen Breitman, Tezos is designed to offer the safety and code correctness needed for digital assets and high-value use cases. It is a decentralized blockchain platform that is self-governing.

Tezos is a smart contract and dApp platform, just like Ethereum, Waves, Neo, but its self-amending cryptographic mechanism makes it different from other platforms.


Following are some of the features of the Tezos platform that distinguish it from other platforms:



    Self-amendment Protocol
    Delegated Proof of Stake Consensus Mechanism
    On-Chain Governance
    Smart Contracts and Formal Verification

2. Stellar

Stellar is an open blockchain network that allows the storing and moving of money. It facilitates you to create, trade and send digital representations of all forms of money, for example, dollars, bitcoin, pesos and a lot more.

Over 69% of banks are currently experimenting with blockchain technology to make their services transparent, seamless, and secure. Stellar is one of the most scalable and significant blockchain platforms that can help build secure and fast fintech applications, tokens and digital assets representing financial assets.

It is an open-source network for payments and currencies. It has no owner; if it has anything, it is owned by the public. It can handle millions of transactions every day. Like Ethereum and Bitcoin, Stellar depends on the blockchain to keep the network synced.

A stellar blockchain platform can be used to issue your own assets, trade peer-to-peer tokens and transform currency while sending.


Below are the significant features of the Stellar Blockchain Network:



    It has a decentralized and open database.
    It enables thousands of transactions in a second.
    It takes a confirmation time of only 3-5 seconds.
    The network allows multi signatures and smart contracts.
    It has a 1% fixed annual inflation.

3. Hyperledger Fabric

Hyperledger Fabric is proposed as a foundation for building apps or solutions with a modular architecture. It allows components, including membership services and consensus, to be plug-and play. It has a wide range of modular and versatile design that meets various industrial use cases.

One of the significant features of Hyperledger Fabric is the enablement of a network of networks. Members of the Fabric network work together, but because businesses want to keep some of their data to remain private, they usually maintain separate relationships within their networks.

For example, a buyer may with different sellers, selling the same product. The transactional relationship between buyers and sellers should be private and not visible to all sellers. It can be made possible via the “channels” feature in Hyperledger Fabric.

Instead of an open and permissionless system, Fabric provides a secure and scalable platform that supports confidential contracts and private transactions.


Here are some of the features of Hyperledger Fabric that makes it different from other platforms:



    Highly modular
    Low latency of finality
    Support for Solidity and EVM
    Multi-language smart contract support
    Pluggable Consensus
    Queryable Data
    Multi-language smart contract support

4. Hyperledger Sawtooth

Hyperledger Sawtooth provides a modular and flexible architecture that separates the core system from the application domain. Therefore, smart contracts can imply the business rules for applications without understanding the underlying design of the core system. It supports different consensus algorithms, including Proof of Elapsed Time (PoET) and Practical Byzantine Fault Tolerance (PBFT).

It is an enterprise blockchain platform used for developing distributed ledger networks and applications. It aims at keeping ledgers distributed and smart contracts secure, specifically for enterprises. It streamlines blockchain app development as developers can specify business rules for their apps using their chosen language.


Following are some of its features that distinguish from other blockchain platforms:



    Private networks with sawtooth permissioning feature
    Parallel transaction execution
    Ethereum contract compatibility with Seth
    Pluggable consensus algorithms
    Separation between the core system and application level

5. EOS

EOS is a blockchain platform designed to develop scalable and secure dApps. It provides dApps’ hosting, smart contracts capability, decentralized storage of enterprise solutions to solve the scalability issues faced by Ethereum and Bitcoin.

The EOS platform eliminates all users’ fees and accomplishes consensus by leveraging multithreading and delegated proof-of-stake algorithm. They have a dedicated community named “EOS forum,” where developers and investors can discuss the platform.


Following are some of the features of the EOS blockchain that make it one of the reliable platforms:



    Usability
    Governance
    Multiprocessing
    Flexibility
    Measurability
    Upgradability
    Permission Schema

6. Openchain

Openchain is an open-source distributed ledger technology designed for organizations willing to issue and manage digital assets in a secure, robust and scalable manner. It uses a different consensus than Bitcoin-based systems, i.e., Partitioned Consensus. Every instance of Openchain has only one authority validating transactions.

Rather than one single central ledger, each organization controls its own Opechain instance to connect. Since it uses a client-server architecture, it is more reliable and efficient than P2P architecture. Also, there is no miner involved in the Openchain blockchain network; therefore, the asset administrator directly validates free and instant transactions.


Here are some of the features of the Openchain blockchain network:



    Modular Design
    Free transactions
    Highly scalable
    2-Way Peg
    Unified API
    Smart Contracts Functionality

7. Corda

Corda is an open-source blockchain platform that allows businesses to transact directly and in strict privacy with smart contracts. It reduces record-keeping and transaction costs by streamlining business processes.

It is a flexible and agile platform that can scale to meet the business requirements. Applications built on Corda, CorDapps are designed and developed to transform businesses across a wide array of sectors, including healthcare, energy, insurance, finance and more.


Features of the Corda blockchain platform that make it one of the ideal platforms:



    Privacy
    Open design
    Interoperability
    Agile and Flexible
    Open Development

8. Tron

Tron is a decentralized blockchain platform that aims to develop a decentralized web. Like Ethereum, Tron allows dApp developers to create and leverage complete protocols via smart contracts on the blockchain.

The Tron platform can handle 2000 transactions per second, which put it on par as compared to major payment processors like Paypal. It has zero transaction fees.

Tron depends on the Delegated-Proof-of-Stake consensus mechanism to secure the blockchain. A DPoS is similar to a proof-of-stake consensus mechanism that allows users to earn passive income whenever they stake their holdings in a network wallet.


Features of Tron Blockchain Network:



    High Scalability
    High Availability
    High Throughput
    Compatibility with EVM
    Multi-language extension
    Eliminating counterfeit chain

9. Hedera Hashpraph

Hedera Hashgraph Platform is a lightning secure, fair and fast platform that does not require computing a heavy proof of work algorithm. It allows developers to develop new innovative and scalable decentralized applications.

Smart contracts in the Hedera Hashgraph platform can be built dynamic just like any other software component. As the platform provides an optional mechanism that enables “binding arbitration”, the smart contracts deployed with a list of public keys of arbitrators can be edited to fix errors or add new features.


Following are some of the features of the Hedera Hashgraph platform:



    Fast
    Fair
    Secure
    Implementation of public BFT Notary Service for Corda
    Connecting Hyperledger Fabric network to Hedera Consensus Service

10. Ethereum

Ethereum is one of the leading blockchain platforms that has a native cryptocurrency called ETH or Ether. Developers use Ethereum to build new applications related to financial apps, decentralized markets, games, cryptocurrency wallets and more.

They have the largest community with core protocol developers, cypherpunks, crypto-economic researchers and mining organizations. It aims to eliminate internet third-parties who save data and track financial instruments.


Below are some of the features of the Ethereum platform:



    Smart Contracts Functionality
    Turing Completeness
    Permissioning
    Privacy
    Rapid Deployment
    Tokenization
