#+TITLE: Defi
      
* tasks
 - graph roam and host at linode
 - story
  - pfolio
    - write reasons from dodo recording
  - uniswap pool, balancer pool, dodo pool
    - PPool only three assets, from balancer
    - since both tokens can get shortage from swapping for third, they can race for regression targets and one can become even more depleted and not useful until arbitraged
  - pricing BlnPaper vs DODOPaper vs UniPaper
    - marginal price from dodo will have to be rewritten as you can no longer rely on either shortage, presume that other side would also lose overflow, instead you should compare shortages or even distance from regression target in either way and better price. in dodo always equilibrium, in balancer never equilibrium, shortage travels between assets?
    - without constant product we lose balancer trait that share of trade after trade doesn't change. instead, share changes with each trade
    - with constant product there is slippage and impermanent loss but infinite liquidity. With market price there is no slippage or loss but liquidity is finite. we want to constraint market price so that trades that deplete liquidity are discouraged. dodo constraints market price by relation between staked and reserve balance, or regression target and current balance, it presumes that shortage in B accompanies overflow in B. We cannot coinstrain market price like in dodo because with multiple assets both balances in a pair can have shortage and instead of keeping staked balance regression would further destabilize portfolio, with one shortage covered with another depleted balance. instead, we want to motivate arbitrage from the highest surplus to the lowest shortage. for that after calculating relation of staked to current you need to calculate relation between those fractions as well.
    - with dodo it would be more profitable to sell token in shortage, but it wouldbe equally profitable to swapit for another depleted asset and one with surplus. to support swapping base shortage with quote surplus we might compare shortages of base and quote, two quotes, or base with average deviation from regression targets in the pool.
    - PPricing only spot price from Dodo and mean from balancer
    - formulas for locational marginal price aka spot price
    - http://www2.econ.iastate.edu/tesfatsi/DerivationLMP.HLLTAC.pdf
    - PPool only AmountOut, take pmm from DODOPaper for each token, weights andmean from BlnPaper for pool
  - contracts $DODO anf $BLN
    - bpool vs dodopair vs UniPair
      - PPool only provide liquidity for all assets, token map and weights from bpool, + what dodo needs
    - lptokens BLNtoken vs dodotoken
    - bfactory vs dodoZoo vs UniFactory
      - PFactory from Bfactory
    - BMath vs DODOMath vs UniswapV2Library
      - PPool only amountOut, oracles from DODOMath, sum for tokens from bmath
  - DODO governance & Balancer governance
    - P governance? g governance?
 - slides
   - pfolio
   - pools
   - pricing
   - contracts
   - governance
 - uml schemes
   - BPool uml & DODOpair
   - bfactory & dodozoo
   - PPool & PFactory
 - code
 - tests
 
* spec
 - DEFI communities
   - lobsterDAO
   - defi telegram channel
 - hedge funds
 - summits
   - solidity summit
   - dubai summit
 - defi
   - MakerDAO
   - Compound
   - Uniswap
   - Sushiswap
   - Mooniswap
   - Kyber
   - Aave
   - Yearn.Finance
   - DODO
   - Balancer
   - Curve
 - oracles
   - chainlink
 - stablecoins
   - usdt
   - usdc
   - usdn
 - erc20 tokens
